### ISSUE TITLE
Changelog / release notes

### ISSUE THREAD

**Issue by grimsa** [origin-energy/java-snapshot-testing#106]
As far as I can tell, it's not obvious what changes are included in different versions, as there are none of:
- GitHub Releases
- `CHANGELOG.md` file
- Tags with version numbers (latest tag is `3.2.6`)

Therefore, e.g. when dependabot raises a PR to upgrade from e.g. 3.3.2 to 3.3.3 version it's not able show what has changed - it only adds a link to commit history: https://github.com/origin-energy/java-snapshot-testing/commits, where there are no corresponding version-bumping commit or tag.

Maybe release process could be improved somehow to make the difference between versions more obvious?

**Comment by jackmatt2** [comment]
Auto TAG is now implemented via `#major, #minor, #patch, or #none` in the commit message
see https://github.com/marketplace/actions/github-tag-bump

I'll look at an action to parse the git commit history instead of adding a `CHANGELOG.md` cause its duplicated effort.
