### ISSUE TITLE
Provide module info

### ISSUE THREAD

**Issue by tobiasdiez** [origin-energy/java-snapshot-testing#108]
When this plugin is used in a modularized environment, then it throws the error
```
/workspaces/jabref/src/test/java/org/jabref/logic/jabrefonline/JabRefOnlineServiceTest.java:6: error: package au.com.origin.snapshots is not visible
import au.com.origin.snapshots.Expect;
                    ^
  (package au.com.origin.snapshots is declared in module org.opentest4j, which does not export it)
/workspaces/jabref/src/test/java/org/jabref/logic/jabrefonline/JabRefOnlineServiceTest.java:7: error: package au.com.origin.snapshots.junit5 is not visible
import au.com.origin.snapshots.junit5.SnapshotExtension;
                              ^
  (package au.com.origin.snapshots.junit5 is declared in module org.opentest4j, which does not export it)
```

Reproduction: https://github.com/JabRef/jabref/pull/7832

I don't have any experience what is needed for junit plugins, but the following might serve as a helpful reference:
- https://github.com/openjdk/skara/blob/master/test/src/main/java/module-info.java
- https://github.com/jcovalent/jcovalent-junit-logging/blob/main/src/main/java/module-info.java
- https://github.com/mtstorm/jlc/blob/master/se.skillytaire.didactic.tools.jlc.api/src/main/java/module-info.java

**Comment by jackmatt2** [comment]
I think shadowJar is causing this issue

https://github.com/origin-energy/java-snapshot-testing/blob/master/build.gradle#L26

**Comment by tobiasdiez** [comment]
Yes, this is probably part of the problem (the other part is the missing module info description).

**Comment by jackmatt2** [comment]
@tobiasdiez 
Can you try with 3.3.9? I have told shadowJar to exclude the stray `module-info.class` from `opentest4j`

**Comment by tobiasdiez** [comment]
Thanks! Now it works with the default serializer. However, if one tries to use json as serializer:
```
    testImplementation 'io.github.origin-energy:java-snapshot-testing-junit5:3.3.9'
    testImplementation 'io.github.origin-energy:java-snapshot-testing-plugin-jackson:3.3.9'
```
Then one gets split-package errors of the form
```
error: module flexmark.ext.gfm.tasklist reads package au.com.origin.snapshots.serializers from both java.snapshot.testing.plugin.jackson and java.snapshot.testing.junit5
```

I think the easiest solution would be to have each serializer in its own package, e.g. `au.com.origin.snapshots.json-serializer` instead of using the same package.

**Comment by jackmatt2** [comment]
Updated the package name in 3.4.0

Note: this is a breaking change and you need to manually update snapshot.properties

See release notes: https://github.com/origin-energy/java-snapshot-testing/releases/tag/3.4.0

**Comment by jackmatt2** [comment]
@tobiasdiez I think the latest version should solve this issue - if not reopen.

**Comment by tobiasdiez** [comment]
I can confirm that its working now! Thanks as lot @jackmatt2 for the quick fixes. ❤️
