### ISSUE TITLE
gradle build java-snapshot-testing-junit4:3.* failed in Android app 

### ISSUE THREAD

**Issue by zhuoran-guo** [origin-energy/java-snapshot-testing#111]
Hello, I want to use java to do an Android snapshot test, according to your information, 
I added dependencies in app/gradle.build as below:
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.protobuf:protobuf-java:3.10.0'

    switch (aarMode) {
        case "nouse":
            implementation project(":chart_edge_ai")
            break

        case "build":
            logger.warn("Build apk from aar file")
            implementation(name: 'chart_edge_ai', ext:'aar')
            break

        case "local":
        case "remote":
            switch (aarType) {
                case "debug":
                    implementation "com.dena.chart:chart-edge-ai-debug:${aarVersion}"
                    break

                case "release":
                    implementation "com.dena.chart:chart-edge-ai:${aarVersion}"
                    break

                default:
                    throw new GradleException("invalid config aar_type='${aarType}'")
            }
            break

        default:
            throw new GradleException("invalid config aar.mode='${aarMode}'")
    }

    implementation 'junit:junit:4.12'
    implementation 'org.assertj:assertj-core:3.10.0'

    // Java Jpeg Library (URL: http://www.javajpeglibrary.com/php/main.php)
    implementation files('libs/javaJpegLib_v1_2.jar')
    implementation 'com.alexdupre:pngj:2.1.2.1'

    implementation 'io.github.origin-energy:java-snapshot-testing-core:3.5.0'
    compileOnly 'org.junit.platform:junit-platform-runner:1.2.0'
    compileOnly 'org.junit.vintage:junit-vintage-engine:5.2.0'

    // Testing
    testImplementation 'org.slf4j:slf4j-simple:2.0.0-alpha0'
    testImplementation 'org.junit.platform:junit-platform-runner:1.2.0'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.2.0'
    testImplementation 'org.assertj:assertj-core:3.11.1'

    // Required java-snapshot-testing peer dependencies
    testImplementation 'com.fasterxml.jackson.core:jackson-core:2.11.3'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.11.3'

    testImplementation 'junit:junit:4.12'
    testImplementation 'androidx.test:core:1.2.0'
    testImplementation 'androidx.test.ext:junit:1.1.1'
    testImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    testImplementation 'org.assertj:assertj-core:3.10.0'
    testImplementation 'org.robolectric:robolectric:4.3'

    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    androidTestImplementation 'androidx.test:rules:1.4.0'
    androidTestImplementation 'androidx.test:runner:1.4.0'
}
```
but when I try to build the gradle in Android, there are a lot of error logs like:

```
> Task :app:checkDebugDuplicateClasses FAILED
> Task :app:mergeDebugJavaResource

> Transform artifact java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) with DexingNoClasspathTransform
/root/.gradle/caches/transforms-2/files-2.1/d464ef42a533d5d14037c47d46c6ba9b/jetified-java-snapshot-testing-junit4-3.5.0.jar: D8: Type shadow.org.assertj.core.api.AbstractArrayAssert is defined multiple times: /root/.gradle/caches/transforms-2/files-2.1/d464ef42a533d5d14037c47d46c6ba9b/jetified-java-snapshot-testing-junit4-3.5.0.jar:shadow/org/assertj/core/api/AbstractArrayAssert.class, /root/.gradle/caches/transforms-2/files-2.1/d464ef42a533d5d14037c47d46c6ba9b/jetified-java-snapshot-testing-junit4-3.5.0.jar:shadow/org/assertj/core/api/AbstractArrayAssert.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class shadow.org.assertj.core.api.AbstractArrayAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
  Duplicate class shadow.org.assertj.core.api.AbstractAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
  Duplicate class shadow.org.assertj.core.api.AbstractAtomicFieldUpdaterAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
  Duplicate class shadow.org.assertj.core.api.AbstractAtomicReferenceAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
```
 it shows the Duplicate error， But left class one and right one are exactly the same, it seems everything install twice at this time,
Do you know how to solve this issue? thank you so much 
By the way, the java-snapshot-testing-junit5:3.* also happened the same error, but java-snapshot-testing-core:3.* can build well

**Comment by jackmatt2** [comment]
It's complaining about `java-snapshot-testing-junit4` but you don't have this listed in your dependencies above. You'll need to find out how/where that dependency is being pulled in.

**Comment by jackmatt2** [comment]
The dependency should be using `testImplementation` too, not `implementation` because you don't want to bundle this with your android artefact.

**Comment by zhuoran-guo** [comment]
@jackmatt2 
thanks for your response,  when I build the gradle in android devices, some error happen: 
if I use implementation 'io.github.origin-energy:java-snapshot-testing-junit4:3.5.0', it shows error like 
```
java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class shadow.org.assertj.core.api.AbstractArrayAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
  Duplicate class shadow.org.assertj.core.api.AbstractAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
```
if  I use the testImplementation 'io.github.origin-energy:java-snapshot-testing-junit4:3.5.0', it shows error like this:
it seems the java-snapshot-testing-junit4 not install in android?
```
> Task :app:compileDebugAndroidTestJavaWithJavac FAILED
/work/android/chart-edge-ai/app/src/androidTest/java/com/dena/chart/edge/ai/sample/ChartEdgeAISnapshotAndroidTest.java:13: error: package au.com.origin.snapshots.junit4 does not exist
import au.com.origin.snapshots.junit4.SnapshotRunner;
```
but if I use the implementation 'io.github.origin-energy:java-snapshot-testing-core:3.5.0', it can build well.
you means that I can not use the implementation in dependency ? 
thank you

**Comment by zhuoran-guo** [comment]
> @jackmatt2 thanks for your response, when I build the gradle in android devices, some error happen: if I use implementation 'io.github.origin-energy:java-snapshot-testing-junit4:3.5.0', it shows error like
> 
> ```
> java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class shadow.org.assertj.core.api.AbstractArrayAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
>   Duplicate class shadow.org.assertj.core.api.AbstractAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
> ```
> 
> if I use the testImplementation 'io.github.origin-energy:java-snapshot-testing-junit4:3.5.0', it shows error like this: it seems the java-snapshot-testing-junit4 not install in android?
> 
> ```
> > Task :app:compileDebugAndroidTestJavaWithJavac FAILED
> /work/android/chart-edge-ai/app/src/androidTest/java/com/dena/chart/edge/ai/sample/ChartEdgeAISnapshotAndroidTest.java:13: error: package au.com.origin.snapshots.junit4 does not exist
> import au.com.origin.snapshots.junit4.SnapshotRunner;
> ```
> 
> but if I use the implementation 'io.github.origin-energy:java-snapshot-testing-core:3.5.0', it can build well. you means that I can not use the implementation in dependency ?
thank you

**Comment by jackmatt2** [comment]
In Gradle
- `implementation` are jars you want to bundle into your package.  In your case - your Android APK bundle.  They can be referenced from both `src/test/java` and `src/main/java`
- `testImplementation` will be available to the `src/test/java` folder and will NOT be included in the APK bundle.  They also can't be found on your `src/main/java` directory

You certainly don't want to include java-snapshot-testing inside your final APK file so `testImplementation` is the correct place to add it.

Are your tests inside the tests folder `src/test/java`.  Maybe Android puts the tests in a different folder for example `src/specs/java`, in this case it might be something like `specsImplementation`.  

The reason it can't be found is that it appears that your tests are not under `src/test/java` and instead somewhere else.

**Comment by zhuoran-guo** [comment]
@jackmatt2 
Hello, thanks for your response,
the thing is that my test is from src/androidTest/java to call and execute the function in src/main/java, thus I need import the snapshot packages  in src/main/java. 
in src/androidTest/java : 
```
@Test
  @MediumTest
  public void inferenceVideoSnapshot() throws Exception {
    snpshotModule.inferenceVideoSnapshot();
```
in src/main/java:
```
public void inferenceVideoSnapshot() throws Exception {
   ............................
   Expect expect = Expect.of(snapshotVerifier, Snapshot.class.getMethod(testName.getMethodName()));
   expect.toMatchSnapshot(results);
}
```
so thats why I need use implementation in the dependency.
But only 'io.github.origin-energy:java-snapshot-testing-core:3.5.0' can build well in this case, could you give me  a JUnit4 example that does not use the JUnit4 extension ?

Thank you so much

**Comment by jackmatt2** [comment]
Pretty sure you need to import it under `androidTestImplementation`, same with all the other peer dependencies.  They should all be under `androidTestImplementation `

```
androidTestImplementation 'io.github.origin-energy:java-snapshot-testing-junit4:3.5.0'
```

**Comment by zhuoran-guo** [comment]
thank you @jackmatt2 
Even if I do the way what you suggestion , I still get this kind of error when build the gradle in Android:
It seems everything install twice ? 

```
> Task :app:checkDebugAndroidTestDuplicateClasses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAndroidTestDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class shadow.org.assertj.core.api.AbstractArrayAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
  Duplicate class shadow.org.assertj.core.api.AbstractAssert found in modules jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0) and jetified-java-snapshot-testing-junit4-3.5.0.jar (io.github.origin-energy:java-snapshot-testing-junit4:3.5.0)
..................
```

Only the 'io.github.origin-energy:java-snapshot-testing-core:3.5.0' can build well in this case, If we can not solve this issue, could you give me a JUnit4 example that does not use the JUnit4 extension ?

**Comment by jackmatt2** [comment]
You can do it this way using only "core"

https://github.com/origin-energy/java-snapshot-testing#using-an-unsupported-framework

**Comment by zhuoran-guo** [comment]
@jackmatt2 
I have try to do this way :

```
private static SnapshotVerifier snapshotVerifier;

@BeforeClass
  static void beforeAll() {
    snapshotVerifier = new SnapshotVerifier(new PropertyResolvingSnapshotConfig(), ChartEdgeAISnapshot.class);
  }

  @AfterClass
  static void afterAll() {
    snapshotVerifier.validateSnapshots();
  }

@Rule
  public TestName testName = new TestName();

public void inferenceIncamDetectionVideoSnapshot() throws Exception {
    Expect expect = Expect.of(snapshotVerifier, ChartEdgeAISnapshot.class.getMethod(testName.getMethodName()));
    expect.toMatchSnapshot(resultsIncam);
  }

```

**Comment by jackmatt2** [comment]
Seems like an issue with `ChartEdgeAISnapshot.class.getMethod(testName.getMethodName())`, run in a debugger and see what each of those elements is returning.

**Comment by zhuoran-guo** [comment]
@jackmatt2 
yes, thanks 
It seems like `ChartEdgeAISnapshot.class.getMethod(testName.getMethodName())` can not get the Method type well like junit5 `testInfo.getTestMethod().get()` do.
Do you know how to get the Method type to use in `Expect.of(snapshotVerifier, Method)` in Java junit4 framework? 

Thank you

**Comment by jackmatt2** [comment]
```
ChartEdgeAISnapshot.class.getMethod("inferenceIncamDetectionVideoSnapshot")
```

**Comment by zhuoran-guo** [comment]
@jackmatt2 
thanks for you help
it works but other error happen:
it seems null object reference happen on snapshot test part 
have you ever meet this kind of error before ? 
```
4) inferenceIncamDetectionVideoSnapshot[ModelVersion=31](com.dena.chart.edge.ai.sample.ChartEdgeAISnapshotAndroidTest)
java.lang.NullPointerException: Attempt to invoke virtual method 'au.com.origin.snapshots.Snapshot au.com.origin.snapshots.SnapshotVerifier.expectCondition(java.lang.reflect.Method, java.lang.Object, java.lang.Object[])' on a null object reference
	at au.com.origin.snapshots.Expect.toMatchSnapshotLegacy(Expect.java:51)
	at au.com.origin.snapshots.Expect.toMatchSnapshot(Expect.java:37)
```

**Comment by jackmatt2** [comment]
I think `snapshotVerifier` might be `null`.  In other words `@BeforeClass` has not ran.  I noticed that you don't have a `@Test` on your test method - that could be the cause.

Use the debugger to check if it's null or not.

**Comment by zhuoran-guo** [comment]
@jackmatt2 
hello, even I add the @Test tag, the same error happen and seems the @BeforeClass has not ran in this case, I think the reason is my test function is in src/main rather than src/androidTest as mentioned before. 
As a countermeasure, I use the `SnapshotVerifier snapshotVerifier = new SnapshotVerifier(new PropertyResolvingSnapshotConfig(), ChartEdgeAISnapshot.class);` to replace the @BeforeClass、and run the `snapshotVerifier.validateSnapshots();` at the end of code to replace the @AfterClass、it seems work and try to generate the .snap file. But I defined the output path of the . snap file in `androidTest/resource/snapshot.properties` as you mentioned in Readme.md , but my test is executed in an android device, so this path should be invalid in the device, thus the error is reported: 
```
4) inferenceIncamDetectionVideoSnapshot[ModelVersion=31](com.dena.chart.edge.ai.sample.ChartEdgeAISnapshotAndroidTest)
java.nio.file.FileSystemException: /src: Read-only file system
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:388)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
```
Do you know how to set the output path of the .snap file on the android device?

Thank you so much

**Comment by jackmatt2** [comment]
OK sound like it's working.

You can control the output of the `__snapshot__` folder from `snapshot.properties`

```
output-dir=src/test/java
```

You might like to change it to

```
output-dir=src/androidTest
```

But it's up to you
