### ISSUE TITLE
Is that possible to generate different .snap file where the same test runs multiple times?

### ISSUE THREAD

**Issue by zhuoran-guo** [origin-energy/java-snapshot-testing#112]
Hello, I have a new question.
In cases my test runs multiple times with different parameters (model version ), and I know I need to set the scenario and it must be unique for each run well, but the problem is that each run results were saved in one .snap file.
`expect.scenario(modelVersion).toMatchSnapshot(Result);`
I want know is it possible to generate difference .snap file respectively depend on the model version, such as .._v39.snap, .._v31.snap?

Thank you so much

**Comment by jackmatt2** [comment]
No this is not supported currently as described in #98 .  To get this working the persistence would need to be abstracted to that users can plugin their own persistence mechanism.
