### ISSUE TITLE
New regex-based snapshot parsing breaks when using `=` in the snapshot name

### ISSUE THREAD

**Issue by jurriaan** [origin-energy/java-snapshot-testing#122]
As seen here the name part of the regex is non-greedy, so it stops matching when it encounters the first `=`:

https://github.com/origin-energy/java-snapshot-testing/blob/5330f07bb15528d58fbd1305d3f615eef79ba635/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/Snapshot.java#L32

We currently have snapshot names like:
```
foo.bar.MailBuilderSpec.generates a correct template when recipientIsCustomer = true
```

Which worked fine on previous versions, but on v4 this is broken and our tests fail, which means this prevents us from upgrading to the latest version.

**Comment by jackmatt2** [comment]
Yeah - I was worried the introduction of the REGEX might break someone :).

The REGEX needs to remain **NON-Greedy** or else it will eat into the actual snapshot.  I might need to restrict the use of the `=` character inside the snapshot name.  

**A Few options:**
1. Error out
2. Change it to something like "equals" and leave a warning message

In any case I think you will need to manually replace the "=" with something else unfortunately.

**Comment by jackmatt2** [comment]
'[', ']' and '=' are no longer allowed in snapshot names and scenario names.

**Comment by koenpunt** [comment]
Seems a bit odd to add restrictions for names, and requiring people using this library to change how they name there snapshots because a the parser can't handle it? Even more so because this worked just fine before adding this feature.

**Comment by jackmatt2** [comment]
Note that this was a major version bump - 3.X to 4.X.  

There were many breaking changes in the 4.X release - especially for people using custom Serializers, Comparators & Reporters that go far beyond the above mechanical refactor. 

Breaking changes are commonly accepted in major version bumps as long as there is an upgrade path for existing users.

In the end there were conflicting concerns. People using custom logic were not happy with how difficult it was to extract information about the snapshot from the raw string.  The introduction of the REGEX gives structure to the snapshot and thus allows this information to be extracted.

The introduction of "headers" allows further metadata to be injected into the snapshot for people using custom logic.  I tended to agree that it was too difficult previously and these changes were necessary.  

Again - it's just a mechanical refactor "find & replace" for existing users to update to version 4.0.
