### ISSUE TITLE
Overwrite the `.snap` instead of writing `.snap.debug`

### ISSUE THREAD

**Issue by nedtwigg** [origin-energy/java-snapshot-testing#131]
Is there a mode for this? Either an environment variable or something in `snapshot.properties`?

**Comment by jackmatt2** [comment]
Yes - see here
https://github.com/origin-energy/java-snapshot-testing#automatically-updating-a-snapshot-via--pupdatesnapshotfilter

**Comment by nedtwigg** [comment]
Oops, thanks! Stupid of me that I couldn't find this on my own. Submitted a little PR to help with the keywords I was stuck on.

**Comment by jackmatt2** [comment]
I think the docs have grown beyond a simple `README.md` now. Might need to do this https://pages.github.com/

**Comment by nedtwigg** [comment]
FWIW, my vote is always to stick with markdown and never go github pages. It was easy for me to tweak the markdown docs to help people who get stuck the same way I got stuck. I would not have bothered to figure out your github pages setup.

Breaking the readme down into multiple markdown files is probably a good idea though.
