### ISSUE TITLE
`updateSnapshot` flag is duplicating snapshot

### ISSUE THREAD

**Issue by jackmatt2** [origin-energy/java-snapshot-testing#15]
`updateSnapshot` is duplicating the snapshot instead of updating the existing one.

**Comment by PieterDeelen** [comment]
We are considering to use java-snapshot-testing. However, we would like to use this "updateSnapshot" functionality, which is currently only working in the latest SNAPSHOT. When do you expect to make a new release containing this fix?

**Comment by jackmatt2** [comment]
Maybe this weekend - I want to get out of BETA and into 2.0.0 - so want to solidify the API.  I can definitely release the BETA before next week.

**Comment by jackmatt2** [comment]
@PieterDeelen `2.0.0` just got released - can take some time to sync with maven central.  There are some breaking changes if you currently use BETA.  See the issue I opened with details.
