### ISSUE TITLE
[question]I could not reference the core's source.

### ISSUE THREAD

**Issue by uk-taniyama** [origin-energy/java-snapshot-testing#152]
I tried to reference the type definition of PropertyResolvingSnapshotConfig and could not reference the source.

```
testImplementation 'io.github.origin-energy:java-snapshot-testing-junit5:4.+'
```

Therefore, the following dependencies were also added, but to no avail.

```
testImplementation 'io.github.origin-energy:java-snapshot-testing-core:4.+'
```

**Comment by jackmatt2** [comment]
Is this still an issue?  core is included with all the implementations already.
