### ISSUE TITLE
Concatenation of multiple strings for snapshot tests

### ISSUE THREAD

**Issue by muehmar** [origin-energy/java-snapshot-testing#159]
In case one has a test case in which one has more than one string (or object) which needs to be snapshot tested, what is the intended/preferred way to do it?

One might think of using different scenarios like in the example with a mail class with subject and body:
```
Mail mail = ...

expect.scenario("subject").toMatchSnapshot(mail.getSubject());
expect.scenario("body").toMatchSnapshot(mail.getBody());
```
but this may be dangerous. If the first scenario fails due to an intended change and one updates the snapshot after the review of the subject change, it will also update the body if it is different but for which the review was not yet done cause the body was never verified after the subject failed. 

So far, I concatenated the strings manually and use then a single `expect.toMatchSnapshot(..)`. But is there a better way or may it be a possibility to support more than one argument in the `toMatchSnapshot` method which are then concatenated with a predefined separator or possibly also a custom one?

**Comment by jackmatt2** [comment]
I would add all the strings to an ArrayList<String>, then snapshot it using the Jackson Serializer
