### ISSUE TITLE
JSON snapshots differ with Jackson 2.16

### ISSUE THREAD

**Issue by TobiX** [origin-energy/java-snapshot-testing#162]
As far as I can see this was broken with https://github.com/FasterXML/jackson-core/pull/1042: The way how spacing is handled in Jackson's PrettyPrinter changed, so https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-plugin-jackson/src/main/java/au/com/origin/snapshots/jackson/serializers/v1/JacksonSnapshotSerializer.java#L35-L41 doesn't work anymore?!?

I might try to work on a fix. Do you need compatibility with older versions of Jackson or should I just switch to the new API?

**Comment by jackmatt2** [comment]
Yeah - we need compatibility with older versions.

Perhaps a new version of the Serializer is required instead of modifying the existing one
```
v2/JacksonSnapshotSerializer.java
```
Change the defaults to use the new Serialiser with the exception of a few places
