### ISSUE TITLE
Make snaphost folder configurable

### ISSUE THREAD

**Issue by wasder** [origin-energy/java-snapshot-testing#21]
It's impossible now to change snapshot folder to resource folder for example.
Implementing custom SnapshotConfig with getSnapshotFolder() only allows to change it relatively to testing class.

**Comment by jackmatt2** [comment]
Just a thought - does overriding `getTestSrcDir()` in your custom `SnapshoConfig` work?

**Comment by wasder** [comment]
> Just a thought - does overriding `getTestSrcDir()` to something like `src/test/resources/` in your custom `SnapshoConfig` work?

I tried it with no luck.

**Comment by jackmatt2** [comment]
I wrote a unit test [here](https://github.com/origin-energy/java-snapshot-testing/blob/1cacb55856dc31e5c96b8f8e6694f44845b0eb34/java-snapshot-testing-core/src/test/java/au/com/origin/snapshots/CustomFolderSnapshotTest.java#L26) and it passed
