### ISSUE TITLE
JSON serializer is not deterministic

### ISSUE THREAD

**Issue by ShishkinDmitriy** [origin-energy/java-snapshot-testing#32]
Hi,

A number of subsequent launches generate different orders of unordered collections. Then the test fails.
The possible approach can be https://stackoverflow.com/questions/45484933/how-to-create-a-deterministic-jackson-objectmapper
But it requires registration of custom comparators.

Best regards,
Dmitry

**Comment by jackmatt2** [comment]
Looks good - will add it

**Comment by jackmatt2** [comment]
Hi @ShishkinDmitriy 

Do you have an example Set implementation you are using for the snapshot that fails?  Have added a few that consistently pass [here](https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/test/java/au/com/origin/snapshots/serializers/__snapshots__/JacksonSnapshotSerializerTest.snap). It might be the order of the `add()` operation which I will try to randomise.

**Comment by ShishkinDmitriy** [comment]
I have no concrete examples. It is just an immutable pojos, with Lombok `@Value` and `@Builder`.
Try to create some pojos, make a snapshot, then serialize by default object mapper and deserialize them back (to change the order of creation of items in the set) and make a snapshot again.

**Comment by jackmatt2** [comment]
@ShishkinDmitriy 

Can you try out the new `DeterministicJacksonSnapshotSerializer` in the latest BETA?  You can use it like this:

```
expect("Hello World").serializer(DeterministicJacksonSnapshotSerializer.class).toMatchSnapshot()
```

Let me know if it has fixed you issues.

**Comment by ShishkinDmitriy** [comment]
I have tried. Looks great! Thanks)
