### ISSUE TITLE
Date serialization

### ISSUE THREAD

**Issue by ShishkinDmitriy** [origin-energy/java-snapshot-testing#33]
Hi,

`LocalDateTime` and other date-related objects are serialized as objects. 
Maybe better and more compact to use ISO string instead?

Best regards,
Dmitry

**Comment by jackmatt2** [comment]
In the latest SNAPSHOT version I have registered JSR module
```
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.registerModule(new Jdk8Module());
```

I believe this should render as an ISO string. I can write a test for it anyway.
```
Date
LocalDate
LocalDateTime
ZonedDateTime
```

Also - the latest version allows you to supply your own serializer via the `@UseSnapshotSerializer` annotation. In addition you can now now configure the mapper yourself too via the `.configure()` method on JacksonSnapshotSerializer.

**Comment by jackmatt2** [comment]
Turns out you need to disable this:
```
objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```

**Comment by jackmatt2** [comment]
New format can be found in this snapshot: https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/test/java/au/com/origin/snapshots/serializers/__snapshots__/JacksonSnapshotSerializerTest.snap

You can use `1.0.0-Beta8-SNAPSHOT` for now, you'll need to enable snapshot repository

For example in Gradle
```
repositories {
   mavenCentral()
   // Enable downloading of Snapshots
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by ShishkinDmitriy** [comment]
Unfortunately, I can't use custom repos, need to wait for a some release version
