### ISSUE TITLE
Get access to configured ObjectMapper from custom junit5 extension

### ISSUE THREAD

**Issue by ShishkinDmitriy** [origin-energy/java-snapshot-testing#41]
Hi,
I have custom framework on top of this projetct. 
I have created junit5 extension as `LazySnapshotExtension extends SnapshotExtension`. I have custom static method that register objects to be match snapshots at the end of test method. Extension holds temp list of objects to be matched. Also these objects are mutable and I did jackson serialiation into temp json to dump object state. On `afterEach` callback I restore objects from this temp list of jsons and call vanilla `toMatchSnapshot()`.
It is work well with simple objects, but with some specific use-cases I have a problem. When object mapper of snapshotVerifier is not the same as my default snapshot in custom extension. Can you add some access for ObjectMapper configured in serializers to custom frameworks can use them?

Or better serialize objects at the moment when `toMatchSnapshot` called and take them in the cache, and after each method do comparison with file. It can relax a requirement of single `expect` for single test method. And I could remove my hand-written extension and use yours :)

Best regards,
Dmitry

**Comment by jackmatt2** [comment]
Hey, Actually serialization does happen when `toMatchSnapshot()` is called - it's just the verification happens later.  The reason it happens later is to support detection on orphan snapshots I guess.

**Comment by jackmatt2** [comment]
I'm assuming you worked around this one - if not re-open.
