### ISSUE TITLE
Does not work with parallel tests

### ISSUE THREAD

**Issue by eladchen** [origin-energy/java-snapshot-testing#43]
Hi, 

I tried using this with parallel tests in junit5, and it seems that
the current codebase assumes a single thread..?

**Comment by jackmatt2** [comment]
https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/SnapshotMatcher.java#L15

Is meant to support this but maybe there is something else that needs to be ThreadLocal too.

**Comment by jackmatt2** [comment]
There appears to be a fundamental flaw in the library concerning parallel tests because all the snapshots are at class level.

I think `'junit.jupiter.testinstance.lifecycle.default': 'per_class'` is the only way parallel will work.
```
test {
    useJUnitPlatform()
    systemProperties = [
            'junit.jupiter.execution.parallel.enabled': true,
            'junit.jupiter.execution.parallel.mode.default': 'concurrent',
            'junit.jupiter.testinstance.lifecycle.default': 'per_class'
    ]
}
```

Can you try this parallel test configuration? I'm not too familiar with it, would be good to compare to your configuration.

**Comment by jackmatt2** [comment]
This is now fixed as part of the 3.0.0 Release.

**Comment by eladchen** [comment]
Hi glad to hear this was addressed.

Is there any specific API I'll need to use (with parallel testing)?

**Comment by jackmatt2** [comment]
Nope - The new api injects `Expect expect` into your test method so just use that. 

The API has been refactored a little - take look at the quick start for an example.  The snapshot format has not changed though so it should be backward compatible.  It does require a mechanical refactor only.

I tested it with these in `junit-platform.properties`
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=concurrent
```

**Comment by eladchen** [comment]
Cool. My only problem is having to add a parameter to every relevant test.

I'll try and find a solution to avoid that (maybe a base class or something)

**Comment by jackmatt2** [comment]
Take a look at this section: https://github.com/origin-energy/java-snapshot-testing#using-an-unsupported-framework

Basically you need a way to create the `Expect` that refers to the current test method being executed.  There may be a way to do that using the beforeEach hook that updated an Expect in your base class.
```
  private Expect expect;

  @BeforeEach
  void beforeEach(TestInfo testInfo) {
   expect = Expect.of(snapshotVerifier, testInfo.getTestMethod().get());
  }
  ```
  
  Then you can refer to Expect directly in your test from the instance variable

**Comment by jackmatt2** [comment]
Hi @eladchen 

I just pushed a new version `3.1.0`.  This allows injecting via an instance variable instead if that helps

You just define this on your test class.
```
private Expect expect
```
