### ISSUE TITLE
Empty .snap files when class has no tests

### ISSUE THREAD

**Issue by idalreadyinuse** [origin-energy/java-snapshot-testing#47]
When a class does not have a test within it, an empty `.snap` file gets generated regardless. This can happen when using the `@Nested` annotation in `junit5`. As an example:
```
@ExtendWith({SnapshotExtension.class})
class SnapshotDemoApplication {
  @Nested
  class NestedClass {
    @Test
    void nestedTest() {
      SnapshotMatcher.expect("hello").toMatchSnapshot();
    }
  }
}
```
Will generate 2 `.snap` files:
- SnapshotDemoApplication.snap (this has nothing in)
- SnapshotDemoApplication$NestedClass.snap (with stuff in)

java-snapshot version: `2.0.0-Beta6`
junit-jupiter: `5.6.3`

Just wondering is this expected behaviour? We are currently working around it by just ignoring those files but it is becoming a bit of a pain.

Many thanks

**Comment by jackmatt2** [comment]
This should be resolved once all items in #44 are done. @juja0 FYI

**Comment by idalreadyinuse** [comment]
That's great. Thanks.

**Comment by idalreadyinuse** [comment]
@jackmatt2  - I have just tested this against `2.1.0` and empty `.snap` files still seems to be created. With the example above I get an empty `SnapshotDemoApplication.snap` file.

Thanks
