### ISSUE TITLE
Parameterized scenario tests - "You can only call 'expect' once per test method"

### ISSUE THREAD

**Issue by GuyJackson** [origin-energy/java-snapshot-testing#50]
In `2.1.0` there seems be an issue with scenario tests. Running the below:

```
@ExtendWith({SnapshotExtension.class})
class SnapshotDemoApplication {

  @ParameterizedTest
  @MethodSource("testData")
  void someTest(String scenario, String testInput) {
    SnapshotMatcher.expect(testInput).json().scenario(scenario).toMatchSnapshot();
  }

  static Stream<Arguments> testData() {

    return Stream.of(
        Arguments.of("Scenario1", "test input 1"),
        Arguments.of("Scenario2", "test input 2"));
  }
}
```
Results in:

> You can only call 'expect' once per test method. Try using array of arguments on a single 'expect' call

Test results:

![image](https://user-images.githubusercontent.com/5394347/100340149-a7d00e80-2fd2-11eb-95b2-afee12d60b11.png)

This **_did_** work in `2.0.0-Beta6`.

Thanks

**Comment by jackmatt2** [comment]
So I have found the issue - I needed to delombok the code but it's related to the `@With` and a varargs in a recent commit.

**Comment by jackmatt2** [comment]
`2.2.0-SNAPSHOT` until I do a release version to maven central
