### ISSUE TITLE
Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8

### ISSUE THREAD

**Issue by wThomas84** [origin-energy/java-snapshot-testing#51]
Hello,

we are really happy using your library in our tests. 
Unfortunately it breaks our logging with the following output:

```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/me/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

Our app that utilises `java-snapshot-testing` is using, among others, Spring Boot that uses SLF4J 1.7.x

We found you use slf4j-api:2.0.0-alpha0 and beta versions. We thus tried to exclude sl4j dependencies from your lib import:

gradle-kotlin:
```
    testImplementation("io.github.origin-energy:java-snapshot-testing-junit5:2.1.0")
    {
        exclude(group = "org.slf4j")
        exclude(group = "log4j")
        exclude(group = "ch.qos.logback")
        // Redundancy is good, is good
        exclude(group = "org.slf4j", module="slf4j-api")
        exclude(group = "org.slf4j", module="slf4j-simple")

    }
```

..but without success. We still get the error above and NO logging.

We are happy and appreciate any suggestions.

Thanks and best Regards
Thomas

**Comment by jackmatt2** [comment]
From that [link](http://www.slf4j.org/codes.html#ignoredBindings) it kind of implies that it couldn't locate a provider for 1.8.

Can you try adding one
```
implementation 'org.slf4j:slf4j-simple:2.0.0-alpha0'
```

**Comment by wThomas84** [comment]
Hey, thanks for the fast answer. 

This works for us; so in our library where we use `java-snapshot-testing` we use the logger provider as you suggested.
Included it as `testImplementation` to not 'pollute' our production code with libs in alpha versions:

```
testImplementation("org.slf4j:slf4j-simple:2.0.0-alpha0")
```

Best regards
Thomas
