### ISSUE TITLE
No Way to extract method arguments for snapshot.

### ISSUE THREAD

**Issue by sourav-jha** [origin-energy/java-snapshot-testing#52]
I am trying to take a snapshot of the method call in the test. In the  json-snapshot.github.io, there is a util class to get it. Can we have something similar in this library.

**Comment by jackmatt2** [comment]
Can you give me a code example of what the test would look like and the .snap file. I'm not understanding the use case.

**Comment by sourav-jha** [comment]
suppose we want to verify all the args of the method call. In json-snapshot.github.io, we have SnapshotUtils.extractArgs("methodName", ...<arg_list _of _snapshot_caputure>);
this provides Map of method arguments.
Which we pass to expect() method.

**Comment by jackmatt2** [comment]
OK just had a look at it.  

```java
    @Test // Snapshot arguments passed to mocked object (from Mockito library)
    public void shouldExtractArgsFromMethod() {
        fakeObject.fakeMethod("test1", 1L, Arrays.asList("listTest1"));
        fakeObject.fakeMethod("test2", 2L, Arrays.asList("listTest1", "listTest2"));

        expect(extractArgs(fakeObject, "fakeMethod", new SnapshotCaptor(String.class), new SnapshotCaptor(Long.class), new SnapshotCaptor(List.class)))
                .toMatchSnapshot();
    }
```

So the problem is, that implementation is coupled to Mockito.  The sole purpose of this library is snapshotting not mocking.

Can I recommend copying that class into your own test code and using as desired.  It should just be a drop-in and work with the existing `expect()` method.
