### ISSUE TITLE
Can you build with slf4j v1.x and publish in another version like 1.2.0 ?

### ISSUE THREAD

**Issue by tumit** [origin-energy/java-snapshot-testing#54]
Hi dev team,

Thanks for your very useful library but I found problem when I run with spring-boot-test and I don't want to use 2 logging provider in implement and testImplement.

So can you build with slf4j v1.x and publish in another version like 1.2.0 ?

**Comment by jackmatt2** [comment]
We won't ship 2 versions but I think we should not be shipping slf4j-api. Instead let the client supply their preferred version.

**Comment by jackmatt2** [comment]
Have released 2.2.1
