### ISSUE TITLE
Snapshot per scenario

### ISSUE THREAD

**Issue by ShishkinDmitriy** [origin-energy/java-snapshot-testing#63]
Hi,

We use snapshot testing a lot and we have a number of test cases for big objects (hundreds of fields).
And we have difficulties with debugging because of huge snapshots (~6k lines for snapshot)..
I think it would be useful to have a snapshot per scenario, not for whole test class. 
Maybe it can be configurable?

Thanks,
Dmitry

**Comment by jackmatt2** [comment]
Can you give an example of what you mean @ShishkinDmitriy?  

We currently support the which might do what you want.
```
expect(parent.getChild1()).scenario("Child 1").toMatchSnapshot();
expect(parent.getChild2()).scenario("Child 2").toMatchSnapshot();
```

**Comment by jackmatt2** [comment]
Closing as I think this is already supported by `.scenario()`, if not please re-open.
