### ISSUE TITLE
Fails to match binary or unicode data

### ISSUE THREAD

**Issue by hbriese** [origin-energy/java-snapshot-testing#64]
#### java-snapshot-testing-junit5   v2.3.0

When matching **binary or Unicode** data, matching succeeds when initially creating the snapshot, but fails when matching against the snapshot.

Base64 encoding the data makes it work as expected, however it'd obviously be nicer to inspect the snapshot without decoding

Using your logo as an example:

#### Fails
```java
File f = new File("origin.png");
byte[] content = Files.readAllBytes(f.toPath());

SnapshotMatcher.expect(content).toMatchSnapshot();
```

#### Works
```java
File f = new File("origin.png");
byte[] content = Files.readAllBytes(f.toPath());

String encoded = Base64.getEncoder().encodeToString(content);
SnapshotMatcher.expect(encoded).toMatchSnapshot();
```

**Comment by jackmatt2** [comment]
There may be a case for a `ByteSerializer` for this use cases.

```java
File f = new File("origin.png");
byte[] content = Files.readAllBytes(f.toPath());

SnapshotMatcher.expect(content).serializer(ByteSerializer.class).toMatchSnapshot();
```

**Comment by jackmatt2** [comment]
I tried to replicate you issue but couldn't get it to fail.  In any case, I'm a bit uncomfortable about adding/supporting byte[] rendered into the snapshot file.  I have added a Base64SnapshotSerializer you can use for byte[] now in version 3.4.0.
