### ISSUE TITLE
Encoding is lost on saving snapshot file leading to snapshot matching failure

### ISSUE THREAD

**Issue by daltonfury42** [origin-energy/java-snapshot-testing#69]
https://github.com/origin-energy/java-snapshot-testing/blob/7b45edd134cf1467cfd6414f956ae1824f4964ca/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/SnapshotFile.java#L110

If the snapshot contains special characters like `®`, `String::getBytes()` returns byte array using the platform's default charset which is leading to the test failing on developer's laptop.  

Is it possible to r make the encoding configurable or set an override for it?

Thanks for this amazing library!

**Comment by jackmatt2** [comment]
We should be able to make it overridable. Were these tests passing on another devs machines?  ie.  is the issue local to specific machines or failing for everyone?

**Comment by jackmatt2** [comment]
@daltonfury42 can you review #70?  I'm just wondering if these is a use case for a client to specify a different one.  Are you aware of any?

**Comment by daltonfury42** [comment]
Forcing UTF-8 would be the easiest thing to do, and it would also work for me. Let me run #70 on my local and confirm in a couple of hours. 

Just that when other existing users upgrade to a newer version, it might lead to snapshots failing for someone, in case snapshots were written in their default non UTF-8. Is this fine?

**Comment by daltonfury42** [comment]
Change looks fine, but I could not test as we are on v2.2.2 of the library.

**Comment by jackmatt2** [comment]
Are you planning on upgrading @daltonfury42 ?  It's a mechanical refactor

- define a `snapshot.properties` file in your resources folder (You can probably delete any @UseSnapshotConfig annotations you used before)
- define an instance variable `private Expect expect`
- move the snapshot object from `expect(YOUR_OBJECT).toMatchSnapshot()` to this  `expect.toMatchSnapshot(YOUR_OBJECT)`

Note: none of you existing snapshots should fail - the format has not changed.

**Comment by jackmatt2** [comment]
Regarding breaking existing clients - I see this as OK.  Snapshots should work the same across systems and have no system dependent side effects.

So the existing code was flawed.

**Comment by jackmatt2** [comment]
Have released 3.2.0

**Comment by daltonfury42** [comment]
Thank you. I have one more feedback, which I have raised as a separate issue #71
