### ISSUE TITLE
Very big snapshots filling up the logs

### ISSUE THREAD

**Issue by daltonfury42** [origin-energy/java-snapshot-testing#71]
Our snapshots are very big. So when they fail, it prints the big JSON to the screen, and it becomes very difficult to read. It also leads to logs which at ~20MB in size, and it also reduces the test performance. 

When printing the snapshot to screen on failure, can we limit to first 100 lines and the last 100 lines? Should this be made configurable? What do you think?

**Comment by jackmatt2** [comment]
We currently support custom reporters.  All you need to do is implement this interface

https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/reporters/SnapshotReporter.java

After that replace your `reporters` key in `snapshot.properties` with your custom one.

**Comment by jackmatt2** [comment]
Take a look at this for an example implementation.  You can probably just extend it and trim() the output as desired: 

https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/reporters/PlainTextSnapshotReporter.java

**Comment by jackmatt2** [comment]
Reopen if this doesn't work for you

**Comment by daltonfury42** [comment]
Thanks, will try and reopen if required.
