### ISSUE TITLE
Missing File Enconding

### ISSUE THREAD

**Issue by rainbow-six3** [origin-energy/java-snapshot-testing#74]
In the method SnapshotFile.cleanup() there is a missing file encoding where leads to false Encoding when rewriting the file.

https://github.com/origin-energy/java-snapshot-testing/blob/32aa4390534396cf80ffc59f164606f94b87fe06/java-snapshot-testing-core/src/main/java/au/com/origin/snapshots/SnapshotFile.java#L126

Simple fix:
` String content = new String(Files.readAllBytes(Paths.get(this.fileName)), StandardCharsets.UTF_8);`

**Comment by jackmatt2** [comment]
Thanks for the PR and the Test particularly.  Will push out 3.2.1 shortly.

**Comment by jackmatt2** [comment]
It's released but it takes a few hours for maven central to propagate.
