### ISSUE TITLE
Custom matchers

### ISSUE THREAD

**Issue by deyceg** [origin-energy/java-snapshot-testing#78]
Hey guys,

Great little tool and was wondering whether or not you had any plans to support custom matchers to only diff a subset of the snapshot tree?

My use case is pretty much https://www.npmjs.com/package/jest-cdk-snapshot.

**Comment by jackmatt2** [comment]
Yes - we do support this. It's called a snapshot comparator

see: https://github.com/origin-energy/java-snapshot-testing#supplying-a-custom-snapshotcomparator

**Comment by deyceg** [comment]
@jackmatt2 Thanks I ended up writing my own comparator, serializer and reporter in the end to get it working. I think it would have been a little easier if these interfaces were generic as I had to do a bit of massaging of types to get it to behave the way I wanted it to (compare a subsection of the actual against the snapshot based on a predicate).

**Comment by jackmatt2** [comment]
I'm doing quite a bit of refactoring in this area. Can you give some examples of API changes that may have made this easier for you?

**Comment by jackmatt2** [comment]
@deyceg In 4.0.0, I have changed the interface to make it more usable (... I think).  It now accepts a "Snapshot" class.  

You can also add headers to inject metadata around your snapshot -  this may make your logic in your comparator/serializer much simpler.  For example you might like to store the class name of the object before serializing it `.header('className', obj.getClass().getName())`, then in your comparator load based on the header value.
