### ISSUE TITLE
How to have parameterized tests with snapshot in Junit4?

### ISSUE THREAD

**Issue by MatthewShao** [origin-energy/java-snapshot-testing#82]
Hello, this project is very helpful for testing our project. Is it possible to have parameterized tests with snapshot in junit4?

We notice that there's a comment saying "This implementation is restricted becase it appears to not support Parameterized tests", we tried to follows the stackoverflow link above in `SnapshotRunner.java`, but it is confusing.

**Comment by jackmatt2** [comment]
Can you try like this

```
expect.scenario(YOUR_PARAMETER).toMatchSnapshot(YOUR_OBJECT);
```

I can't recall why that comment is there.  Maybe things have moved on since and it can be removed.

**Comment by MatthewShao** [comment]
Thank you for responding so quickly! `scenario` partially solve the problm now. It would be great to have parameterized feature from Junit, since it would make testing more organized.

**Comment by jackmatt2** [comment]
Each parameterized test needs a unique name (thus the scenario).  I'm not exactly sure what you mean by parameterized feature from JUnit because you should be able to use that just fine along with `scenario`

Can you supply an example of what isn't working?

**Comment by MatthewShao** [comment]
Yes, `scenario` works fine, here our code.
```java
    @Test
    public void testAll() throws Exception {
        String path = getClass().getResource("").getPath();
        File[] samples = new File(path).listFiles();
        for (File f : samples) {
            String result = run(f);
            String name = f.getName();
            expect.scenario(f.getName()).toMatchSnapshot(result);
        }
    }
```
However, we could only puts all assertions (`toMatchSnapshot`) in one test, which will stop at the first time it meets a failure.
What I really hope is run snapshot with the Parameterized runer like from junit4 offical document:
```java
import static org.junit.Assert.assertEquals;

import java.util.Arrays;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

@RunWith(Parameterized.class)
public class FibonacciTest {

    @Parameters(name = "{index}: fib({0})={1}")
    public static Iterable<Object[]> data() {
        return Arrays.asList(new Object[][] { 
                 { 0, 0 }, { 1, 1 }, { 2, 1 }, { 3, 2 }, { 4, 3 }, { 5, 5 }, { 6, 8 }
           });
    }

    private int input;
    private int expected;

    public FibonacciTest(int input, int expected) {
        this.input = input;
        this.expected = expected;
    }

    @Test
    public void test() {
        assertEquals(expected, Fibonacci.compute(input));
    }
}
```
This could separate assertion in multiple tests according to the parameters, like:
![image](https://user-images.githubusercontent.com/9366279/131784249-3b45e233-489f-478b-b813-38bb4560b3f3.png)
It will make the testing more organized and easier to follow the errors, right?

**Comment by MatthewShao** [comment]
Thanks! This is exactly what we are looking for.

**Comment by jackmatt2** [comment]
I've worked out a solution using `@Rule` & `@ClassRule`, will get it out for release in the next couple of days. In the meantime you can use the above solution.

**Comment by jackmatt2** [comment]
v3.2.5 There is now a solution to this problem using JUnit4 Rules instead of the Runner.  See the README.md for an example.
