### ISSUE TITLE
Test case inputs in snapshot files and multiple test cases per test method

### ISSUE THREAD

**Issue by douira** [origin-energy/java-snapshot-testing#89]
This is essentially two questions but since they are slightly related I'm putting them in one issue. Feel free to do as you wish with this issue since it's mostly just a question and not a bug report or similar.

## Multiple test cases per test method
Is it possible to have multiple snapshots per test method?

## Test case inputs in the snapshot file
I'm testing a my GLSL program transformation library and would like to do snapshot tests for input/outputs of the transformer. The library's basic operation is that it parses a string, does some transformation on the parse tree and then prints it back into a string.

Now it would be nice if I could use this snapshot testing framework to process a large number of input/output test cases automatically. I'm envisioning a snapshot test file for one particular behavior being tested to look something like this:

```plaintext
=====
the first test case consisting of 20 lines of code...
>>>>>
the same code but with the transformation applied...
=====
the second test case code...
>>>>>
the expected output for the second test case
...
```
Since this library already has a snapshot test file format, maybe it could be expanded to support something like this. (this example was written for a separate question not specific to this library)

The corresponding Java code could be something like this where it would read the test cases from a file with the name of the test or as given in an annotation:

```java
@SnapshotName("expression_replacement_simple")
@Test
public String testExpressionReplacement(String input) {
  return transform(input); //insert library usage here
}
```

Putting strings for each of the test cases directly in the Java code would be impractical, especially since visually comparing the input and output should be easy. I could of course just read the input code myself, but then the inputs and outputs would still be in separate files and formats. Thanks for any hints!

**Comment by jackmatt2** [comment]
**Multiple test cases per test method**
Yes - use `.scenario()` method to distinguish the snapshots

**Test case inputs in the snapshot file**
Yes - you should use `.scenario` along with the way your test framework handles parameterized tests.

Junit5 example: https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-junit5/src/test/java/au/com/origin/snapshots/SnapshotParameterTest.java

**Comment by douira** [comment]
Thanks for the very fast answer! So the first question was clearly just a matter of me properly reading the README. The fact that the provided example is written in Groovy is a little confusing but the example you linked makes it clearer.

As for the second question: I see the `.snap` file for the scenario test contains the scenario inputs and outputs provided in the test. The important part for me is that the inputs I'm dealing with are too long to include in a java code file. They can be many (like 20 for example) lines long and are each slightly different.

Can I write a snapshot file without including any of the inputs in the actual java code but rather putting them right next to the outputs in the snapshot file? Like in the [snapshot file](https://github.com/origin-energy/java-snapshot-testing/blob/master/java-snapshot-testing-junit5/src/test/java/au/com/origin/snapshots/__snapshots__/SnapshotParameterTest.snap) for the test you linked, but without `test input 1` etc needing to be put in the `SnapshotParameterTest.java` and only being in `SnapshotParameterTest.snap`. I'm willing to write additional utility code if this is something that this library doesn't support natively. (but it would be nice to know if this is even feasible)

For illustration, I concrete example would be the following short input:
```glsl
#version 5432

#extension extension_name: require

layout(location = 0) out vec3 layoutOne;
layout(location = 1) out vec3 layoutTwo;

uniform sampler2D Sampler;

varying vec2 varyVec;

struct Struct {
    vec4 vector;
    float number;
};

#define DIRECTIVE_NAME DIRECTIVE_VALUE

Struct arrayName[arraySize];

void functionDef(const in float param) {
  functionCall();
}
```

with the corresponding slightly differing output:
```glsl
#version 5432

#extension extension_name: require

layout(location = 0) out vec3 layoutOne;
layout(location = 1) out vec3 layoutTwo;

uniform sampler2D Sampler;

varying vec2 varyVec;

struct Struct {
    vec4 vector;
    float number;
};

#define DIRECTIVE_NAME DIRECTIVE_VALUE

Struct arrayName[arraySize];

void functionDef(const in float param) {
  setup_function();
  functionCall();
}
```

Putting many strings like the first one in the java source file would be impractical.

**Comment by jackmatt2** [comment]
So you wouldn't use the above code as the scenario name - that's what you are snapshotting. The scenario name would be a meaningful representation of the above.  Maybe the filename, index number or something else.  The only requirement is that it's short and consistent.  It should not in anyway be derived from the content you are snapshotting or else you will get an entirely new snapshot when it changes.

For the parameterized inputs consider a Map or separate fields that represent the `key` & `value`

**Comment by douira** [comment]
I've implemented an actual test similar to how you suggested it:
```java
static Stream<Arguments> injectNodeProvider() {
  return Stream.of(
      Arguments.of("empty", ""),
      Arguments.of("simple", "#version 5432\nbar;"));
}

@ParameterizedTest
@MethodSource("injectNodeProvider")
void testInjectNode(String scenario, String input) {
  testCode = input;
  setupParsing();
  setupCollector();
  transformation = new Transformation() {
    @Override
    protected void createPhases() {
      addPhase(new RunPhase() {
        @Override
        protected void run(TranslationUnitContext ctx) {
          injectExternalDeclaration("foo;\n", InjectionPoint.BEFORE_VERSION);
        }
      });
    }
  };
  collector.registerTransformation(transformation);
  collector.transformTree(tree, tokenStream);
  
  var output = PrintVisitor.printTree(tokenStream, tree);
  expect.scenario(scenario).toMatchSnapshot(input, "\n>>>>>\n", output);
}
```

I'm currently using a map for storing the inputs. The outputs are put in a snapshot file by the library automatically.

However, I can't continue to put the inputs in the java code because it can get pretty long. (see previous comment, I wouldn't want to put such an input in the code) Is there a solution for this? Can JUnit load test parameters from snapshot files instead of needing to put them in the java code?

**Comment by jackmatt2** [comment]
Yep - use filenames as the input and load them in the test method in this case.

**Comment by douira** [comment]
Ok so putting the inputs directly in the snapshot files like this is not possible?
```
io.github.douira.glsl_transformer.transform.TransformationPhaseTest.testInjectNode[empty]=[


>>>>>

foo
]


io.github.douira.glsl_transformer.transform.TransformationPhaseTest.testInjectNode[simple]=[
#version 5432
bar;

>>>>>

#version 5432
foo;bar;
]
```

**Comment by jackmatt2** [comment]
Yes it's possible but this is my understanding of what you are trying to solve

- You have a large input text
- You apply a transformation to the above text to produce a transformed output

You don't want to hard code the input into the JAVA test as it's large and cumbersome.

You can create an input file
/input/a.txt

The filename will be the `scenario` and you will snapshot both the contents of the file along with the transformation.

This is entirely doable and you only need a single argument (not 2)

```
static Stream<Arguments> injectNodeProvider() {
  return Stream.of(
      Arguments.of("empty"), //input/empty.txt
      Arguments.of("simple")); //input/simple.txt
}

@ParameterizedTest
@MethodSource("injectNodeProvider")
void testInjectNode(String filename) {
  String input = // Load "file" from your filesystem based on filename passed
  String transformed = applyTransformation(input);
  expect.scenario(filename).toMatchSnapshot(input, "\n>>>>>\n", output);
}
```

**Comment by douira** [comment]
Thanks for the confirmation. That's what I thought of too. I'll implement it like you suggest then. Thank you for your time and help. If there's anything else, I'll report back.
