### ISSUE TITLE
Allow one snapshot file per test with only the output of the snapshot

### ISSUE THREAD

**Issue by scharf** [origin-energy/java-snapshot-testing#98]
Having all tests in one `.snap` file makes it sometimes hard to use a diff to see the differences of a single test.

The default snapshot name could just contain the `ClassName + "." + TestName + extension`

If I serialize the test as `.json` (or  something else, like html) it would be nice if the snapshot would only contain json and have a `.json` extension, so that I can inspect it in an editor with syntax highlight.

**Comment by jackmatt2** [comment]
The latest version 3.3.0 will output all the tests in the debug file (even if they pass).  That would make diff comparison easier I think.  There is an issue with deleting debug filed in the latest version though so you might need to wait until 3.3.1

**Comment by jackmatt2** [comment]
I'm closing this as .debug now contain all snapshots making DIFF comparison easy.
