### ISSUE TITLE
3.3.0 - Successful test run leaves .debug files around

### ISSUE THREAD

**Issue by grimsa** [origin-energy/java-snapshot-testing#99]
We recently upgraded to 3.3.0 and observed a change in behavior - running tests now leaves a large number of `.snap.debug` files, even if all tests are successful.

The content of the file is identical to the `.snap` file.

This seems to have been added in this PR: https://github.com/origin-energy/java-snapshot-testing/pull/97 and it was even predicted in one of PR review comments:
> Leaving debug files around will annoy/confuse existing users - they need to be deleted if they are exactly the same as the *.snap file.

**Comment by jackmatt2** [comment]
Thanks - I did run some tests locally before I merged but the .debug files were removed.  There might be some issues with the comparison being used.

**Comment by jackmatt2** [comment]
In the meantime use 3.2.7

**Comment by grimsa** [comment]
@jackmatt2 Maybe it could be related to line endings? Debug files seem to be created consistently on Windows, but not on Linux.

**Comment by fredrikkarlsson-pervanovo** [comment]
A related thought, shouldn't the debug file be removed when all of its data entries are in the snap file? When running just one test case and not the whole test file, the debug file will not be equal snap file anyways, or am I missing something?

**Comment by jackmatt2** [comment]
Yep, I didn't consider the effect of running a single test - maybe this feature introduced a regression here too.  I'm now feeling I should revert the commit.

- Run single test that passes (debug should be deleted)
- Run single test that fails (debug should remain)
- Run suite that passes (debug should be deleted)
- Run suite that fails (debug should remain)

**Comment by jackmatt2** [comment]
@mmiesiak I have needed to revert #91 

Issues that have been identified are:

1. Does not work on Windows machines (Although this may be a separate issue)
2. Does not work when a single test is run though the IDE (debug is created but never deleted if the snapshots match)

**Comment by fredrikkarlsson-pervanovo** [comment]
Can you put it on a feature branch and maybe add the hacktoberfest opt-in to the repo? (https://hacktoberfest.com/participation/#maintainers)

**Comment by jackmatt2** [comment]
@grimsa Do you have people using Windows & Linux machines on the same codebase?  Do the snapshots work in both environments when checked out and the tests are ran?  

I'm just hoping line endings are consistent across platforms ie "\n" and not "\r\n".  I think GIT might actually check them in as "\n" so potentially they are in fact inserting as "\r\n" on Windows machines.

**Comment by grimsa** [comment]
> Do you have people using Windows & Linux machines on the same codebase? Do the snapshots work in both environments when checked out and the tests are ran?

@jackmatt2 Yes and yes.

> I'm just hoping line endings are consistent across platforms ie "\n" and not "\r\n". I think GIT might actually check them in as "\n" so potentially they are in fact inserting as "\r\n" on Windows machines.

Downloaded a raw snapshot file from Github web UI - it had LF endings (as expected - git normalizes them to LF):
![image](https://user-images.githubusercontent.com/8446128/190166572-ce4172d4-85ba-441b-977a-95503d830a03.png)

Inspected a checked out snapshot file on a Windows machine - it has CR LF line endings (also as expected - git converts them to CR LF on checkout):
![image](https://user-images.githubusercontent.com/8446128/190167066-0a8e3aed-ed5b-41c1-903a-cc0bc122db7a.png)

`.gitattributes` we use:
```
# Handle line endings automatically for files detected as text
# and leave all files detected as binary untouched.
* text=auto

#
# The above will handle all files NOT found below
#
# These files are text and should be normalized (Convert crlf => lf)
*.java          text
# ... some other code and configuration files, but .snap is not one of them
```

After deleting the file an running the test (to recreate the snapshot), the snapshot contains just LF line endings:
![image](https://user-images.githubusercontent.com/8446128/190167929-99cc3172-c028-41a6-856a-e93b3bdaa228.png)

**Comment by grimsa** [comment]
Should be fixed in https://github.com/origin-energy/java-snapshot-testing/pull/101
